export const data = [
  {
    Name: "Shirley Chisholm",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33821503",
    imagePath: "assets/images/Shirley-Chisholm.jpg",
  },
  {
    Name: "500 Building",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811461",
    imagePath: "assets/images/500Bldg.jpg",
  },
  {
    Name: "Hostos X-ray Hell No We Won’t Close",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811735",
    imagePath: "assets/images/HostosX.jpg",
  },
  {
    Name: "Baseball Team",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811594",
    imagePath: "assets/images/HostosBaseball.jpg",
  },
  {
    Name: "Hostos Basketball",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811592",
    imagePath: "assets/images/HostosBasketball.jpg",
  },
  {
    Name: "Tito Puente",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811526",
    imagePath: "assets/images/Tito.jpg",
  },
  {
    Name: "Student Group Shot by the Parking Meter",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811686",
    imagePath: "assets/images/GroupMeter.jpg",
  },
  {
    Name: "Magda Group Shot",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811885",
    imagePath: "assets/images/MagdaGroup.jpg",
  },
  {
    Name: "Marta Rivera Classroom",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811851",
    imagePath: "assets/images/MartaClassroom.jpg",
  },
  {
    Name: "Bicentennial Hostos March",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811730",
    imagePath: "assets/images/BiMarch.jpg",
  },
  {
    Name: "Spanish March 149th",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811454",
    imagePath: "assets/images/SpanishMarch.jpg",
  },
  {
    Name: "United 500 March with Peter Roman",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811451",
    imagePath: "assets/images/United500.jpg",
  },
  {
    Name: "Give Us More to Learn March",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811749",
    imagePath: "assets/images/GiveUsMarch.jpg",
  },
  {
    Name: "Taw Kwon Do",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/stable/community.33811749",
    href: "https://www.jstor.org/stable/community.33811597",
    imagePath: "assets/images/Taw.jpg",
  },
  {
    Name: "Serrano’s Speech Outside 475 Building",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811733",
    imagePath: "assets/images/SerranoSpeech.jpg",
  },
  {
    Name: "Dignitaries Faculty",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811762",
    imagePath: "assets/images/TwoFalc.jpg",
  },
  {
    Name: "Student in Leopard Print",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811902",
    imagePath: "assets/images/LeoPrint.jpg",
  },
  {
    Name: "Colgate Float",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811693",
    imagePath: "assets/images/ColgateFloat.jpg",
  },
  {
    Name: "Performers",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811505",
    imagePath: "assets/images/Performers.jpg",
  },
  {
    Name: "Linda Anderson and Peter Roman",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811879",
    imagePath: "assets/images/Linda.jpg",
  },
  {
    Name: "Ribbon Cutting with Dignitaries",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811838",
    imagePath: "assets/images/Ribbon.jpg",
  },
  {
    Name: "Savoy Containers",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811540",
    imagePath: "assets/images/Containers.jpg",
  },
  {
    Name: "Women at the Post Office",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811588",
    imagePath: "assets/images/PostOffice.jpg",
  },
  {
    Name: "Preciado",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811881",
    imagePath: "assets/images/Preciado.jpg",
  },
  {
    Name: "CeliaCruzTitoHM",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811521",
    imagePath: "assets/images/CeliaCruzTitoHM.jpg",
  },
  {
    Name: "LeoKeithExercise",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811473",
    imagePath: "assets/images/LeoKeithExercise.jpg",
  },
  {
    Name: "FitnessCenterHostos",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811829",
    imagePath: "assets/images/FitnessCenterHostos.jpg",
  },
  {
    Name: "HostosMusician",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811530",
    imagePath: "assets/images/HostosMusician.jpg",
  },
  {
    Name: "savoyDestruction",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811537",
    imagePath: "assets/images/savoyDestruction.jpg",
  },
  {
    Name: "SteveDelgadoHM",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811874",
    imagePath: "assets/images/SteveDelgadoHM.jpg",
  },
  {
    Name: "AlliedNursesHM",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811836",
    imagePath: "assets/images/AlliedNursesHM.jpg",
  },
  {
    Name: "ConcourseBlockedHM",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811746",
    imagePath: "assets/images/ConcourseBlockedHM.jpg",
  },
  {
    Name: "BetteKerrAndStudents",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811502",
    imagePath: "assets/images/BetteKerrAndStudents.jpg",
  },
  {
    Name: "StudentSpeakerHM",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811844",
    imagePath: "assets/images/StudentSpeakerHM.jpg",
  },
  {
    Name: "DemoKochPlans",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811742",
    imagePath: "assets/images/DemoKochPlans.jpg",
  },
  {
    Name: "WeNeedMoreSpaceDemo",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811741",
    imagePath: "assets/images/WeNeedMoreSpaceDemo.jpg",
  },
  {
    Name: "ConCoursePlaza",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310510",
    imagePath: "assets/images/ConCoursePlaza.jpg",
  },
  {
    Name: "RiverAve161",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310510",
    imagePath: "assets/images/RiverAve161.jpg",
  },
  {
    Name: "GradHallCardinal",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310510",
    imagePath: "assets/images/GradHallCardinal.jpg",
  },
  {
    Name: "gradHallMan",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311289",
    imagePath: "assets/images/gradHallMan.jpg",
  },
  {
    Name: "MadgaSpringTime",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310831",
    imagePath: "assets/images/MadgaSpringTime.jpg",
  },
  {
    Name: "KidsAtTrain",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310834",
    imagePath: "assets/images/KidsAtTrain.jpg",
  },
  {
    Name: "FreeDomAngela",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310837",
    imagePath: "assets/images/FreeDomAngela.jpg",
  },
  {
    Name: "MagdaSchoolStrike",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310750",
    imagePath: "assets/images/MagdaSchoolStrike.jpg",
  },
  {
    Name: "StudentOnRoof475",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310753",
    imagePath: "assets/images/StudentOnRoof475.jpg",
  },
  {
    Name: "GeneralActivitiesMagda",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310759",
    imagePath: "assets/images/GeneralActivitiesMagda.jpg",
  },
  {
    Name: "Mancuso Edwards",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811805",
    imagePath: "assets/images/MancusoEdwards.jpg",
  },
  {
    Name: "Group Faculty Shot",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811464",
    imagePath: "assets/images/FacultyShot.jpg",
  },
  {
    Name: "Students with Certificates",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811691",
    imagePath: "assets/images/Certificates.jpg",
  },
  {
    Name: "Dominican Student Group",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811843",
    imagePath: "assets/images/Dominican.jpg",
  },
  {
    Name: "Concourse Graduation",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811695",
    imagePath: "assets/images/Graduation.jpg",
  },
  {
    Name: "Savoy Construction",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811760",
    imagePath: "assets/images/Savoy.jpg",
  },
  {
    Name: "Pres and Wally",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811545",
    imagePath: "assets/images/Pres.jpg",
  },
  {
    Name: "500 Building Aerial View",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811582",
    imagePath: "assets/images/Aerial.jpg",
  },
  {
    Name: "President, Tito, and Ferrer",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33821528",
    imagePath: "assets/images/President.jpg",
  },
  {
    Name: "Bridge Construction on Grand Concourse",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811752",
    imagePath: "assets/images/Construction.jpg",
  },
  {
    Name: "Jose Diaz",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811915",
    imagePath: "assets/images/Jose.jpg",
  },
  {
    Name: "500 Building Demonstration",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811455",
    imagePath: "assets/images/Demonstration.jpg",
  },
  {
    Name: "Ribbon Cutting for Hostos Bridge",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811869",
    imagePath: "assets/images/RibbonHostos.jpg",
  },
  {
    Name: "Street Shot 149th Hostos",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811542",
    imagePath: "assets/images/Street.jpg",
  },
  {
    Name: "Dental Hygiene Lab",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811839",
    imagePath: "assets/images/Dental.jpg",
  },
  {
    Name: "Art Group with Wally",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811761",
    imagePath: "assets/images/Art.jpg",
  },
  {
    Name: "Martorell with Santiago",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811790",
    imagePath: "assets/images/Martorell.jpg",
  },
  {
    Name: "Student and their baby",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811495",
    imagePath: "assets/images/baby.jpg",
  },
  {
    Name: "Bench at 475",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811586",
    imagePath: "assets/images/475Bench.jpg",
  },
  {
    Name: "Library Card Catalogue",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811475",
    imagePath: "assets/images/Library.jpg",
  },
  {
    Name: "Bette Kerr and Pat P",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811560",
    imagePath: "assets/images/Bette.jpg",
  },
  {
    Name: "Student Celebration",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811688",
    imagePath: "assets/images/hugging.jpg",
  },
  {
    Name: "Badillo",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811608",
    imagePath: "assets/images/Badillo.jpg",
  },
  {
    Name: "Orlando and friends",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811466",
    imagePath: "assets/images/Orlando.jpg",
  },
  {
    Name: "Isabel Li Advising Students",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "",
    imagePath: "assets/images/Isabel.jpg",
  },
  {
    Name: "Student Protest at Bronx County Bldg",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811720",
    imagePath: "assets/images/ProtestBronx.jpg",
  },
  {
    Name: "Bicentennial with Hostos March",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811730",
    imagePath: "assets/images/BicentennialMarch.jpg",
  },
  {
    Name: "Library Staff with Jose Diaz",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811857",
    imagePath: "assets/images/LibraryStaff.jpg",
  },
  {
    Name: "Koch and Hostos President",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811813",
    imagePath: "assets/images/Koch.jpg",
  },
  {
    Name: "Mbabuike",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811494",
    imagePath: "assets/images/Mbabuike.jpg",
  },
  {
    Name: "Library Computer Terminals",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811557",
    imagePath: "assets/images/Terminals.jpg",
  },
  {
    Name: "Jerry Meyer",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811462",
    imagePath: "assets/images/JerryMeyer.jpg",
  },
  {
    Name: "Public Safety",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811763",
    imagePath: "assets/images/publicsafety.jpg",
  },
  {
    Name: "Chase Manhattan",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811754",
    imagePath: "assets/images/Chase.jpg",
  },
  {
    Name: "Children of Students",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811736",
    imagePath: "assets/images/Children.jpg",
  },
  {
    Name: "March thru East Harlem",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811732",
    imagePath: "assets/images/EastHarlem.jpg",
  },
  {
    Name: "Mancuso Edwards with Serrano",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811490",
    imagePath: "assets/images/Mancuso.jpg",
  },
  {
    Name: "Students Posing at Event",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811893",
    imagePath: "assets/images/Posing.jpg",
  },
  {
    Name: "Serrano and Koch",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811627",
    imagePath: "assets/images/SerranoandKoch.jpg",
  },
  {
    Name: "Students with Bette Kerr",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811499",
    imagePath: "assets/images/BetteKerr.jpg",
  },
  {
    Name: "Classroom Scene",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811707",
    imagePath: "assets/images/classroomScene.jpg",
  },
  {
    Name: "Photography Lab",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811849",
    imagePath: "assets/images/PhotographyLab.jpg",
  },
  {
    Name: "Saw Horse",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811749",
    imagePath: "assets/images/SawHorse.jpg",
  },
  {
    Name: "500 Building with poster and chain link",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811737",
    imagePath: "assets/images/chainlink.jpg",
  },
  {
    Name: "Students with Window and Bridge",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811543",
    imagePath: "assets/images/WindowBridge.jpg",
  },
  {
    Name: "Nurses with Plaques",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811835",
    imagePath: "assets/images/NursesPlaques.jpg",
  },
  {
    Name: "Faculty with Cynthia",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811876",
    imagePath: "assets/images/Cynthia.jpg",
  },
  {
    Name: "Student Speaker in 475",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811835",
    imagePath: "assets/images/Speaker475.jpg",
  },
  {
    Name: "Faculty",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811766",
    imagePath: "assets/images/GroupFaculty1.jpg",
  },
  {
    Name: "Do Not Close Our Home",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811734",
    imagePath: "assets/images/OurHome.jpg",
  },
  {
    Name: "475 Public Plaza with Benches",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33821513",
    imagePath: "assets/images/PublicPlaza.jpg",
  },
  {
    Name: "Struggle for 500 Banner Michangelo",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811713",
    imagePath: "assets/images/BannerMichangelo.jpg",
  },
  {
    Name: "Celia Cruz and Tito",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811589",
    imagePath: "assets/images/CeliaCruzTito.jpg",
  },
  {
    Name: "Downtown Mass Rally",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811463",
    imagePath: "assets/images/DowntownMass.jpg",
  },
  {
    Name: "Children with Save Hostos Sign",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811751",
    imagePath: "assets/images/ChildrenSign.jpg",
  },
  {
    Name: "Magda with Santiago",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811679",
    imagePath: "assets/images/MagdaSantiago.jpg",
  },
  {
    Name: "Group in Library",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811847",
    imagePath: "assets/images/GroupLibrary.jpg",
  },
  {
    Name: "Student Group Boom Boxes",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811687",
    imagePath: "assets/images/GroupBoomBoxes.jpg",
  },
  {
    Name: "149th Street Demonstation",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811711",
    imagePath: "assets/images/DemonstationStreet.jpg",
  },
  {
    Name: "Aerial Shot Top of Tower",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811581",
    imagePath: "assets/images/TopofTower.jpg",
  },
  {
    Name: "Celia and Tito",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811521",
    imagePath: "assets/images/CeliaTito.jpg",
  },
  {
    Name: "Badillo and Chiesa with Hostos Portrait",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811812",
    imagePath: "assets/images/BadilloChiesaPortrait.jpg",
  },
  {
    Name: "Magda,Bernabe,  and Dinkins",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33821501",
    imagePath: "assets/images/MagdaBernabeDinkins.jpg",
  },
  {
    Name: "4 Students",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811683",
    imagePath: "assets/images/4Students.jpg",
  },
  {
    Name: "Mancuso with Arts and Culture",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811756",
    imagePath: "assets/images/MancusoArtsCulture.jpg",
  },
  {
    Name: "X-ray Protest",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811735",
    imagePath: "assets/images/X-rayProtest.jpg",
  },
  {
    Name: "Concourse closed for Rally Post Office",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811746",
    imagePath: "assets/images/RallyPostOffice.jpg",
  },
  {
    Name: "Magda with a Torch",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811886",
    imagePath: "assets/images/MagdaTorch.jpg",
  },
  {
    Name: "Students waiting at Financial Aid",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811685",
    imagePath: "assets/images/FinancialAid.jpg",
  },
  {
    Name: "David Gomez at the Gala",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811681",
    imagePath: "assets/images/DavidGala.jpg",
  },
  {
    Name: "Children at Table",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811677",
    imagePath: "assets/images/ChildrenTable.jpg",
  },
  {
    Name: "Theater with Isabel",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811533",
    imagePath: "assets/images/TheaterIsabel.jpg",
  },
  {
    Name: "Honor Students",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811833",
    imagePath: "assets/images/HonorStudents.jpg",
  },
  {
    Name: "Protester Close Up",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811714",
    imagePath: "assets/images/ProtesterClose.jpg",
  },
  {
    Name: "Pat P with Students",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811553",
    imagePath: "assets/images/PatP.jpg",
  },

  {
    Name: "Professor Reading Proclamation",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811477",
    imagePath: "assets/images/ProfessorReading.jpg",
  },
  {
    Name: "Professor with Student",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811912",
    imagePath: "assets/images/StudentProfessor.jpg",
  },
  {
    Name: "Hostos with Power Test and Castle",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811639",
    imagePath: "assets/images/CastlePowerHostos.jpg",
  },
  {
    Name: "Students Hanging Banner 500",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811459",
    imagePath: "assets/images/HangingBanner500.jpg",
  },
  {
    Name: "Stimola with Students",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811900",
    imagePath: "assets/images/StimolaStudents.jpg",
  },
  {
    Name: "Shirley Chishom with Badillo",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811491",
    imagePath: "assets/images/ChishomBadillo.jpg",
  },
  {
    Name: "Cuomo",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811598",
    imagePath: "assets/images/Cuomo.jpg",
  },

  {
    Name: "Mancuso with Model of New Campus",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811794",
    imagePath: "assets/images/ModelNewCampus.jpg",
  },

  {
    Name: "Angela Davis Mic",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339307",
    imagePath: "assets/images/AngelaSpeech.jpg",
  },
  {
    Name: "Angela Davis Lecture",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339291",
    imagePath: "assets/images/AngelaDavisLecture.jpg",
  },
  {
    Name: "Students of Angela Davis",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339306",
    imagePath: "assets/images/AngelaStudents.jpg",
  },
  {
    Name: "Angela Davis",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339298",
    imagePath: "assets/images/AG.jpg",
  },
  {
    Name: "Open Mic",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339295",
    imagePath: "assets/images/AngelaD.jpg",
  },
  {
    Name: "Hostos Community College",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311619",
    imagePath: "assets/images/HCCBG.jpg",
  },
  {
    Name: "Ford Auto Shop",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311252",
    imagePath: "assets/images/FordAuto.jpg",
  },
  {
    Name: "Subway View",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311079",
    imagePath: "assets/images/subwayHCC.jpg",
  },
  {
    Name: "National Theater",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339410",
    imagePath: "assets/images/NT.jpg",
  },
  {
    Name: "Grand Ford Walton",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311259",
    imagePath: "assets/images/GrandFort.jpg",
  },
  {
    Name: "161st Street River Avenue",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310506",
    imagePath: "assets/images/161.jpg",
  },
  {
    Name: "Yankee Stadium",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310507",
    imagePath: "assets/images/YankeeS.jpg",
  },
  {
    Name: "Tunnel Side 161",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310510",
    imagePath: "assets/images/TunnelSide161.jpg",
  },
  {
    Name: "Subway Platform",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310513",
    imagePath: "assets/images/SubwayPlatform.jpg",
  },
  {
    Name: "Herman Badillo",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339381",
    imagePath: "assets/images/HermanBadillo1.jpg",
  },
  {
    Name: "Badillo Classroom Students",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339382",
    imagePath: "assets/images/BadilloC.jpg",
  },
  {
    Name: "Office Hours",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310589",
    imagePath: "assets/images/OfficeHours.jpg",
  },
  {
    Name: "Teacher and Student",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310582",
    imagePath: "assets/images/1on1.jpg",
  },
  {
    Name: "Teacher Advising",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310586",
    imagePath: "assets/images/TeacherAdvising.jpg",
  },
  {
    Name: "Teacher and Coffee",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310591",
    imagePath: "assets/images/TeacherCoffee.jpg",
  },
  {
    Name: "Dental Hygiene Program",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310984",
    imagePath: "assets/images/DentalHygiene.jpg",
  },
  {
    Name: "Dental Hygiene Room",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310941",
    imagePath: "assets/images/DentalRoom.jpg",
  },
  {
    Name: "President Abrams Visit",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310952",
    imagePath: "assets/images/DentalPres.jpg",
  },
  {
    Name: "Dental Table Clinic",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310966",
    imagePath: "assets/images/DentalTable.jpg",
  },
  {
    Name: "Dental Table Clinic Close Up",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310973",
    imagePath: "assets/images/TableClinicKid.jpg",
  },
  {
    Name: "Criminal Court 161st Street",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311230",
    imagePath: "assets/images/Court161.jpg",
  },
  {
    Name: "Grand Ford For Sale",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311251",
    imagePath: "assets/images/Grandford4sale.jpg",
  },
  {
    Name: "Student w/ Professor",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311206",
    imagePath: "assets/images/StudentAndProf.jpg",
  },
  {
    Name: "Students in the Waiting Room",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311199",
    imagePath: "assets/images/2students.jpg",
  },
  {
    Name: "Grand Ford with Castle",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311257",
    imagePath: "assets/images/CastleGrandFord.jpg",
  },
  {
    Name: "Diner Cigar",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311208",
    imagePath: "assets/images/DinerCigar.jpg",
  },
  {
    Name: "Professor Sketching",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311204",
    imagePath: "assets/images/ProfSketching.jpg",
  },
  {
    Name: "Student with an Afro",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311213",
    imagePath: "assets/images/StudentAfro.jpg",
  },
  {
    Name: "Students At The Diner",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311209",
    imagePath: "assets/images/StudentAtDiner.jpg",
  },
  {
    Name: "Campus Ground",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311070",
    imagePath: "assets/images/CampusGround.jpg",
  },
  {
    Name: "Subway with Power",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311062",
    imagePath: "assets/images/TestAndCastle.jpg",
  },
  {
    Name: "School Party",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310769",
    imagePath: "assets/images/PartyTime.jpg",
  },
  {
    Name: "Kool Cigs Party",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310773",
    imagePath: "assets/images/KoolCigs.jpg",
  },
  {
    Name: "Pat P at Party Demure",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310772",
    imagePath: "assets/images/PatPParty.jpg",
  },
  {
    Name: "Group Party Shot",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310765",
    imagePath: "assets/images/GroupPartyShop.jpg",
  },
  {
    Name: "Magda Vasillov in Savoy",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310762",
    imagePath: "assets/images/MagdaVasillov.jpg",
  },
  {
    Name: "Students in Savoy",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310761",
    imagePath: "assets/images/StudentSavoy.jpg",
  },
  {
    Name: "Graduation",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310867",
    imagePath: "assets/images/3graduation.jpg",
  },
  {
    Name: "Cardinal Hayes Graduation",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311281",
    imagePath: "assets/images/WideGrad.jpg",
  },
  {
    Name: "Hayes Two Women",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310887",
    imagePath: "assets/images/TwoHayes.jpg",
  },
  {
    Name: "Graduation Singing",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310873",
    imagePath: "assets/images/GradSing.jpg",
  },
  {
    Name: "Graduation Doorway",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310884",
    imagePath: "assets/images/GradDoor.jpg",
  },
  {
    Name: "Meyer At Graduation",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311630",
    imagePath: "assets/images/MeyerGrad.jpg",
  },
  {
    Name: "De Leon Close Up",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310871",
    imagePath: "assets/images/LeonGrad.jpg",
  },
  {
    Name: "Cameraman at Graduation",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311272",
    imagePath: "assets/images/CameraGrad.jpg",
  },
  {
    Name: "Student Speaker",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311276",
    imagePath: "assets/images/SpeakerGrad.jpg",
  },
  {
    Name: "Post Office",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310645",
    imagePath: "assets/images/PostOfficeKid.jpg",
  },
  {
    Name: "First Day of Classes",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310636",
    imagePath: "assets/images/FirstDayOfClass.jpg",
  },
  {
    Name: "Barbed Wire Entrance",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310639",
    imagePath: "assets/images/BarbedWire.jpg",
  },
  {
    Name: "Classroom with students",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310631",
    imagePath: "assets/images/StudentsAfter.jpg",
  },
  {
    Name: "Basketball Game",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311139",
    imagePath: "assets/images/BasketballSitdown.jpg",
  },
  {
    Name: "Crowd During a Game",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311166",
    imagePath: "assets/images/CrowdBB.jpg",
  },
  {
    Name: "BBall Team",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339432",
    imagePath: "assets/images/BBallHCC.jpg",
  },
  {
    Name: "Rad Tech Students",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310699",
    imagePath: "assets/images/RadTechStudents.jpg",
  },
  {
    Name: "Track Team",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311114",
    imagePath: "assets/images/TrackTeamHCC.jpg",
  },
  {
    Name: "Volleyball Team",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311194",
    imagePath: "assets/images/VballTeam.jpg",
  },
  {
    Name: "Hostos Pool",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310670",
    imagePath: "assets/images/HostosPool.jpg",
  },
  {
    Name: "De Leon in the Library",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339317",
    imagePath: "assets/images/DeLeonLib.jpg",
  },
  {
    Name: "Group Citation in Office",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339340",
    imagePath: "assets/images/OfficeGroupCite.jpg",
  },
  {
    Name: "Head Shots",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339346",
    imagePath: "assets/images/6HeadShots.jpg",
  },
  {
    Name: "Pura Belpre",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311290",
    imagePath: "assets/images/PuraB.jpg",
  },
  {
    Name: "Students w/ Typewriter",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310693",
    imagePath: "assets/images/TypewriterS.jpg",
  },
  {
    Name: "Rafael Cortada",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339366",
    imagePath: "assets/images/RafaelC.jpg",
  },
  {
    Name: "Recruitments",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310490",
    imagePath: "assets/images/recruitments.jpg",
  },
  {
    Name: "Recruitment",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310493",
    imagePath: "assets/images/Recruitment.jpg",
  },
  {
    Name: "Recruitment Group Shot",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310493",
    imagePath: "assets/images/RecruitmentG.jpg",
  },
  {
    Name: "Signing Model City Grants",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310535",
    imagePath: "assets/images/SigningModal.jpg",
  },
  {
    Name: "Casual Model Signing",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310542",
    imagePath: "assets/images/ModelSign.jpg",
  },
  {
    Name: "475 Courtyard Clean up",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310828",
    imagePath: "assets/images/CourtyardClean.jpg",
  },
  {
    Name: "Courtyard MTA Entrance",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310832",
    imagePath: "assets/images/MTACourtyard.jpg",
  },
  {
    Name: "Demonstration Striking People",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310810",
    imagePath: "assets/images/StrikingDemonstration.jpg",
  },
  {
    Name: "Lecture Room Projection",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310847",
    imagePath: "assets/images/LectureProjection.jpg",
  },
  {
    Name: "Hostos Hallway",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310862",
    imagePath: "assets/images/HallwayHostos.jpg",
  },
  {
    Name: "Hallway Meeting",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310854",
    imagePath: "assets/images/MeetingHallway.jpg",
  },
  {
    Name: "Bullhorn Meeting",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310813",
    imagePath: "assets/images/MeetingBullhorn.jpg",
  },
  {
    Name: "Classroom w/ Projection",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310845",
    imagePath: "assets/images/ProjectionClassroom.jpg",
  },
  {
    Name: "Trash Stud Scene",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310835",
    imagePath: "assets/images/StudTrash.jpg",
  },
  {
    Name: "Free Angela Davis",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310838",
    imagePath: "assets/images/FreeAngela.jpg",
  },
  {
    Name: "Student at Work",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310863",
    imagePath: "assets/images/WorkStudent1.jpg",
  },
  {
    Name: "Chalkboard Cigarette",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310822",
    imagePath: "assets/images/CigaretteChalkboard.jpg",
  },
  {
    Name: "Mechanical Hand",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310827",
    imagePath: "assets/images/HandMechanical.jpg",
  },
  {
    Name: "GC Demo Pitney",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310784",
    imagePath: "assets/images/PitneyGC.jpg",
  },
  {
    Name: "475 Yard Trash",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310830",
    imagePath: "assets/images/TrashYard.jpg",
  },
  {
    Name: "1970s Afro",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310811",
    imagePath: "assets/images/1970sAfro.jpg",
  },
  {
    Name: "Anti-War Rally",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310737",
    imagePath: "assets/images/AntiWarRally.jpg",
  },
  {
    Name: "VPA Students Hands in Air",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310990",
    imagePath: "assets/images/StudentsAir.jpg",
  },
  {
    Name: "Students in Study Hall",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311292",
    imagePath: "assets/images/StudyStudentsHall.jpg",
  },
  {
    Name: "Solo BBall Player",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339452",
    imagePath: "assets/images/PlayerSolo.jpg",
  },
  {
    Name: "Student Strike GCP",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310744",
    imagePath: "assets/images/StudentStrikeGCP.jpg",
  },
  {
    Name: "Pattern Subway",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311665",
    imagePath: "assets/images/patternsubway.jpg",
  },
  {
    Name: "Performer Straw Skirt",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "",
    imagePath: "assets/images/StrawPerformer.jpg",
  },
  {
    Name: "Nurses Roundtable",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310894",
    imagePath: "assets/images/RoundtableNurses.jpg",
  },
  {
    Name: "Herman Badillo classroom",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339380",
    imagePath: "assets/images/BadilloHerman.jpg",
  },
  {
    Name: "Flora Mancuso Edwards",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311309",
    imagePath: "assets/images/EdwardsFlora.jpg",
  },
  {
    Name: "Flora MC President’s Office",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311616",
    imagePath: "assets/images/OfficeFlora.jpg",
  },
  {
    Name: "Cardinal Hayes Graduation WS",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311282",
    imagePath: "assets/images/GraduationWS.jpg",
  },
  {
    Name: "Student Lounge",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311229",
    imagePath: "assets/images/LoungeStudent.jpg",
  },
  {
    Name: "GC Strike Cop",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310749",
    imagePath: "assets/images/StrikeCop.jpg",
  },
  {
    Name: "Dental Cleaning",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310961",
    imagePath: "assets/images/CleaningDental.jpg",
  },
  {
    Name: "Name",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310751",
    imagePath: "assets/images/AngelaDavisLecture.jpg",
  },
  {
    Name: "Student Striking GC",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310751",
    imagePath: "assets/images/StudentGCStriking.jpg",
  },
  {
    Name: "500BLDG Media",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310732",
    imagePath: "assets/images/500BLDGMedia.jpg",
  },
  {
    Name: "Collage Assembly Groups Photo",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311002",
    imagePath: "assets/images/GroupsAssemblyPhoto.jpg",
  },
  {
    Name: "BBall Afro Player",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.20339440",
    imagePath: "assets/images/BBallPlayerAfro.jpg",
  },
  {
    Name: "Collage Assembly Student Alone",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311009",
    imagePath: "assets/images/AssemblyCollage.jpg",
  },
  {
    Name: "Student Cheerleader",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311186",
    imagePath: "assets/images/CheerleaderStudent.jpg",
  },
  {
    Name: "Dance Class Studio",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19311024",
    imagePath: "assets/images/StudioClassDance.jpg",
  },
  {
    Name: "Theater West Side Story",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310679",
    imagePath: "assets/images/WestSSTheather.jpg",
  },
  {
    Name: "Dental H Abrams",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310952",
    imagePath: "assets/images/DentalHAbrams.jpg",
  },
  {
    Name: "Track Team Van",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "",
    imagePath: "assets/images/VanTeam.jpg",
  },
  {
    Name: "Students Holding Hands",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310994",
    imagePath: "assets/images/HoldHands.jpg",
  },
  {
    Name: "West Side Story",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310677",
    imagePath: "assets/images/WestSidestory.jpg",
  },
  {
    Name: "149th Street",
    Title: "Magda Vasillov",
    Date: "1973",
    Collection: "https://www.jstor.org/site/hostos/magda-vasillov-photographs",
    href: "https://www.jstor.org/stable/community.19310729",
    imagePath: "assets/images/StreetScenes149th.jpg",
  },
];
