export const data = [
  {
    Name: "Shirley Chisholm",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33821503",
    imagePath: "assets/images/Shirley-Chisholm.jpg",
  },
  {
    Name: "500 Building",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811461",
    imagePath: "assets/images/500Bldg.jpg",
  },
  {
    Name: "Hostos X-ray Hell No We Won’t Close",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811735",
    imagePath: "assets/images/HostosX.jpg",
  },
  {
    Name: "Baseball Team",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811594",
    imagePath: "assets/images/HostosBaseball.jpg",
  },
  {
    Name: "Hostos Basketball",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811592",
    imagePath: "assets/images/HostosBasketball.jpg",
  },
  {
    Name: "Tito Puente",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811526",
    imagePath: "assets/images/Tito.jpg",
  },
  {
    Name: "Student Group Shot by the Parking Meter",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811686",
    imagePath: "assets/images/GroupMeter.jpg",
  },
  {
    Name: "Magda Group Shot",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811885",
    imagePath: "assets/images/MagdaGroup.jpg",
  },
  {
    Name: "Marta Rivera Classroom",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811851",
    imagePath: "assets/images/MartaClassroom.jpg",
  },
  {
    Name: "Bicentennial Hostos March",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811730",
    imagePath: "assets/images/BiMarch.jpg",
  },
  {
    Name: "Spanish March 149th",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811454",
    imagePath: "assets/images/SpanishMarch.jpg",
  },
  {
    Name: "United 500 March with Peter Roman",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811451",
    imagePath: "assets/images/United500.jpg",
  },
  {
    Name: "Give Us More to Learn March",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811749",
    imagePath: "assets/images/GiveUsMarch.jpg",
  },
  {
    Name: "Taw Kwon Do",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/stable/community.33811749",
    href: "https://www.jstor.org/stable/community.33811597",
    imagePath: "assets/images/Taw.jpg",
  },
  {
    Name: "Serrano’s Speech Outside 475 Building",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811733",
    imagePath: "assets/images/SerranoSpeech.jpg",
  },
  {
    Name: "Dignitaries Faculty",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811762",
    imagePath: "assets/images/TwoFalc.jpg",
  },
  {
    Name: "Student in Leopard Print",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811902",
    imagePath: "assets/images/LeoPrint.jpg",
  },
  {
    Name: "Colgate Float",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811693",
    imagePath: "assets/images/ColgateFloat.jpg",
  },
  {
    Name: "Performers",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811505",
    imagePath: "assets/images/Performers.jpg",
  },
  {
    Name: "Linda Anderson and Peter Roman",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811879",
    imagePath: "assets/images/Linda.jpg",
  },
  {
    Name: "Ribbon Cutting with Dignitaries",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811838",
    imagePath: "assets/images/Ribbon.jpg",
  },
  {
    Name: "Savoy Containers",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811540",
    imagePath: "assets/images/Containers.jpg",
  },
  {
    Name: "Women at the Post Office",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811588",
    imagePath: "assets/images/PostOffice.jpg",
  },
  {
    Name: "Preciado",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811881",
    imagePath: "assets/images/Preciado.jpg",
  },
  {
    Name: "Mancuso Edwards",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811805",
    imagePath: "assets/images/MancusoEdwards.jpg",
  },
  {
    Name: "Group Faculty Shot",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811464",
    imagePath: "assets/images/FacultyShot.jpg",
  },
  {
    Name: "Students with Certificates",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811691",
    imagePath: "assets/images/Certificates.jpg",
  },
  {
    Name: "Dominican Student Group",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811843",
    imagePath: "assets/images/Dominican.jpg",
  },
  {
    Name: "Concourse Graduation",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811695",
    imagePath: "assets/images/Graduation.jpg",
  },
  {
    Name: "Savoy Construction",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811760",
    imagePath: "assets/images/Savoy.jpg",
  },
  {
    Name: "Pres and Wally",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811545",
    imagePath: "assets/images/Pres.jpg",
  },
  {
    Name: "500 Building Aerial View",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811582",
    imagePath: "assets/images/Aerial.jpg",
  },
  {
    Name: "President, Tito, and Ferrer",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33821528",
    imagePath: "assets/images/President.jpg",
  },
  {
    Name: "Bridge Construction on Grand Concourse",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811752",
    imagePath: "assets/images/Construction.jpg",
  },
  {
    Name: "Jose Diaz",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811915",
    imagePath: "assets/images/Jose.jpg",
  },
  {
    Name: "500 Building Demonstration",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811455",
    imagePath: "assets/images/Demonstration.jpg",
  },
  {
    Name: "Ribbon Cutting for Hostos Bridge",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811869",
    imagePath: "assets/images/RibbonHostos.jpg",
  },
  {
    Name: "Street Shot 149th Hostos",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811542",
    imagePath: "assets/images/Street.jpg",
  },
  {
    Name: "Dental Hygiene Lab",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811839",
    imagePath: "assets/images/Dental.jpg",
  },
  {
    Name: "Art Group with Wally",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811761",
    imagePath: "assets/images/Art.jpg",
  },
  {
    Name: "Martorell with Santiago",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811790",
    imagePath: "assets/images/Martorell.jpg",
  },
  {
    Name: "Student and their baby",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811495",
    imagePath: "assets/images/baby.jpg",
  },
  {
    Name: "Bench at 475",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811586",
    imagePath: "assets/images/475Bench.jpg",
  },
  {
    Name: "Library Card Catalogue",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811475",
    imagePath: "assets/images/Library.jpg",
  },
  {
    Name: "Bette Kerr and Pat P",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811560",
    imagePath: "assets/images/Bette.jpg",
  },
  {
    Name: "Student Celebration",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811688",
    imagePath: "assets/images/hugging.jpg",
  },
  {
    Name: "Badillo",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811608",
    imagePath: "assets/images/Badillo.jpg",
  },
  {
    Name: "Orlando and friends",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811466",
    imagePath: "assets/images/Orlando.jpg",
  },
  {
    Name: "Isabel Li Advising Students",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "",
    imagePath: "assets/images/Isabel.jpg",
  },
  {
    Name: "Student Protest at Bronx County Bldg",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811720",
    imagePath: "assets/images/ProtestBronx.jpg",
  },
  {
    Name: "Bicentennial with Hostos March",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811730",
    imagePath: "assets/images/BicentennialMarch.jpg",
  },
  {
    Name: "Library Staff with Jose Diaz",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811857",
    imagePath: "assets/images/LibraryStaff.jpg",
  },
  {
    Name: "Koch and Hostos President",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811813",
    imagePath: "assets/images/Koch.jpg",
  },
  {
    Name: "Mbabuike",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811494",
    imagePath: "assets/images/Mbabuike.jpg",
  },
  {
    Name: "Library Computer Terminals",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811557",
    imagePath: "assets/images/Terminals.jpg",
  },
  {
    Name: "Jerry Meyer",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811462",
    imagePath: "assets/images/JerryMeyer.jpg",
  },
  {
    Name: "Public Safety",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811763",
    imagePath: "assets/images/publicsafety.jpg",
  },
  {
    Name: "Chase Manhattan",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811754",
    imagePath: "assets/images/Chase.jpg",
  },
  {
    Name: "Children of Students",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811736",
    imagePath: "assets/images/Children.jpg",
  },
  {
    Name: "March thru East Harlem",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811732",
    imagePath: "assets/images/EastHarlem.jpg",
  },
  {
    Name: "Mancuso Edwards with Serrano",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811490",
    imagePath: "assets/images/Mancuso.jpg",
  },
  {
    Name: "Students Posing at Event",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811893",
    imagePath: "assets/images/Posing.jpg",
  },
  {
    Name: "Serrano and Koch",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811627",
    imagePath: "assets/images/SerranoandKoch.jpg",
  },
  {
    Name: "Students with Bette Kerr",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811499",
    imagePath: "assets/images/BetteKerr.jpg",
  },
  {
    Name: "Classroom Scene",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811707",
    imagePath: "assets/images/classroomScene.jpg",
  },
  {
    Name: "Photography Lab",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811849",
    imagePath: "assets/images/PhotographyLab.jpg",
  },
  {
    Name: "Saw Horse",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811749",
    imagePath: "assets/images/SawHorse.jpg",
  },
  {
    Name: "500 Building with poster and chain link",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811737",
    imagePath: "assets/images/chainlink.jpg",
  },
  {
    Name: "Students with Window and Bridge",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811543",
    imagePath: "assets/images/WindowBridge.jpg",
  },
  {
    Name: "Nurses with Plaques",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811835",
    imagePath: "assets/images/NursesPlaques.jpg",
  },
  {
    Name: "Faculty with Cynthia",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811876",
    imagePath: "assets/images/Cynthia.jpg",
  },
  {
    Name: "Student Speaker in 475",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811835",
    imagePath: "assets/images/Speaker475.jpg",
  },
  {
    Name: "Faculty",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811766",
    imagePath: "assets/images/GroupFaculty1.jpg",
  },
  {
    Name: "Do Not Close Our Home",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811734",
    imagePath: "assets/images/OurHome.jpg",
  },
  {
    Name: "475 Public Plaza with Benches",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33821513",
    imagePath: "assets/images/PublicPlaza.jpg",
  },
  {
    Name: "Struggle for 500 Banner Michangelo",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811713",
    imagePath: "assets/images/BannerMichangelo.jpg",
  },
  {
    Name: "Celia Cruz and Tito",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811589",
    imagePath: "assets/images/CeliaCruzTito.jpg",
  },
  {
    Name: "Downtown Mass Rally",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811463",
    imagePath: "assets/images/DowntownMass.jpg",
  },
  {
    Name: "Children with Save Hostos Sign",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811751",
    imagePath: "assets/images/ChildrenSign.jpg",
  },
  {
    Name: "Magda with Santiago",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811679",
    imagePath: "assets/images/MagdaSantiago.jpg",
  },
  {
    Name: "Group in Library",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811847",
    imagePath: "assets/images/GroupLibrary.jpg",
  },
  {
    Name: "Student Group Boom Boxes",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811687",
    imagePath: "assets/images/GroupBoomBoxes.jpg",
  },
  {
    Name: "149th Street Demonstation",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811711",
    imagePath: "assets/images/DemonstationStreet.jpg",
  },
  {
    Name: "Aerial Shot Top of Tower",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811581",
    imagePath: "assets/images/TopofTower.jpg",
  },
  {
    Name: "Celia and Tito",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811521",
    imagePath: "assets/images/CeliaTito.jpg",
  },
  {
    Name: "Badillo and Chiesa with Hostos Portrait",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811812",
    imagePath: "assets/images/BadilloChiesaPortrait.jpg",
  },
  {
    Name: "Magda,Bernabe,  and Dinkins",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33821501",
    imagePath: "assets/images/MagdaBernabeDinkins.jpg",
  },
  {
    Name: "4 Students",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811683",
    imagePath: "assets/images/4Students.jpg",
  },
  {
    Name: "Mancuso with Arts and Culture",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811756",
    imagePath: "assets/images/MancusoArtsCulture.jpg",
  },
  {
    Name: "X-ray Protest",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811735",
    imagePath: "assets/images/X-rayProtest.jpg",
  },
  {
    Name: "Concourse closed for Rally Post Office",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811746",
    imagePath: "assets/images/RallyPostOffice.jpg",
  },
  {
    Name: "Magda with a Torch",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811886",
    imagePath: "assets/images/MagdaTorch.jpg",
  },
  {
    Name: "Students waiting at Financial Aid",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811685",
    imagePath: "assets/images/FinancialAid.jpg",
  },
  {
    Name: "David Gomez at the Gala",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811681",
    imagePath: "assets/images/DavidGala.jpg",
  },
  {
    Name: "Children at Table",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811677",
    imagePath: "assets/images/ChildrenTable.jpg",
  },
  {
    Name: "Theater with Isabel",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811533",
    imagePath: "assets/images/TheaterIsabel.jpg",
  },
  {
    Name: "Honor Students",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811833",
    imagePath: "assets/images/HonorStudents.jpg",
  },
  {
    Name: "Protester Close Up",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811714",
    imagePath: "assets/images/ProtesterClose.jpg",
  },
  {
    Name: "Pat P with Students",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811553",
    imagePath: "assets/images/PatP.jpg",
  },

  {
    Name: "Professor Reading Proclamation",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811477",
    imagePath: "assets/images/ProfessorReading.jpg",
  },
  {
    Name: "Professor with Student",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811912",
    imagePath: "assets/images/StudentProfessor.jpg",
  },
  {
    Name: "Hostos with Power Test and Castle",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811639",
    imagePath: "assets/images/CastlePowerHostos.jpg",
  },
  {
    Name: "Students Hanging Banner 500",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811459",
    imagePath: "assets/images/HangingBanner500.jpg",
  },
  {
    Name: "Stimola with Students",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811900",
    imagePath: "assets/images/StimolaStudents.jpg",
  },
  {
    Name: "Shirley Chishom with Badillo",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811491",
    imagePath: "assets/images/ChishomBadillo.jpg",
  },
  {
    Name: "Cuomo",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811598",
    imagePath: "assets/images/Cuomo.jpg",
  },

  {
    Name: "Mancuso with Model of New Campus",
    Title: "Hostos Moments",
    Date: "1968-2008",
    Collection: "https://www.jstor.org/site/hostos/hostos-moments1968-2008",
    href: "https://www.jstor.org/stable/community.33811794",
    imagePath: "assets/images/ModelNewCampus.jpg",
  },
];
